export type { IconProps } from './types'
export type { SportIconKey } from './sportIcons'
export { sportIcons } from './sportIcons'

export { default as IconBallAmericanFootball } from './icons/IconBallAmericanFootball.vue'
export { default as IconBallBaseball } from './icons/IconBallBaseball.vue'
export { default as IconBallBasketball } from './icons/IconBallBasketball.vue'
export { default as IconBallFootball } from './icons/IconBallFootball.vue'
export { default as IconBallRugby } from './icons/IconBallRugby.vue'
export { default as IconBallTennis } from './icons/IconBallTennis.vue'
export { default as IconBoxingGlove } from './icons/IconBoxingGlove.vue'
export { default as IconFlag } from './icons/IconFlag.vue'
export { default as IconGolf } from './icons/IconGolf.vue'
export { default as IconHockey } from './icons/IconHockey.vue'
export { default as IconSteeringWheel } from './icons/IconSteeringWheel.vue'
export { default as IconVolleyball } from './icons/IconVolleyball.vue'
export { default as IconWaterPolo } from './icons/IconWaterPolo.vue'

export { default as IconArrowLeft } from './icons/IconArrowLeft.vue'
export { default as IconArrowsSort } from './icons/IconArrowsSort.vue'
export { default as IconBrandGithub } from './icons/IconBrandGithub.vue'
export { default as IconCircleFilled } from './icons/IconCircleFilled.vue'
export { default as IconDogHouse } from './icons/IconDogHouse.vue'
export { default as IconGripVertical } from './icons/IconGripVertical.vue'
export { default as IconLogin } from './icons/IconLogin.vue'
export { default as IconLogout } from './icons/IconLogout.vue'
export { default as IconMoon } from './icons/IconMoon.vue'
export { default as IconPencil } from './icons/IconPencil.vue'
export { default as IconPin } from './icons/IconPin.vue'
export { default as IconPinnedOff } from './icons/IconPinnedOff.vue'
export { default as IconPlus } from './icons/IconPlus.vue'
export { default as IconSearch } from './icons/IconSearch.vue'
export { default as IconSun } from './icons/IconSun.vue'
export { default as IconTrash } from './icons/IconTrash.vue'
export { default as IconX } from './icons/IconX.vue'
